### ISSUE TITLE
Criação modelo físico

### ISSUE THREAD

**Issue by edrikfsteiner** [edrikfsteiner/aluguel-carros#1]

**Comment by edrikfsteiner** [comment]
Tabelas cliente, carro, modelo, marca, endereço, aluguel, reserva, pagamento, logs

**Comment by gustavoniero** [comment]
// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table cliente {
  cd_cliente int [primary key]
  nm_cliente varchar(200)
  telefone int
  email varchar(200)
  cpf int
}

Table veículos {
  placa char(7) [primary key]
  ano date
  cor varchar(10)
  chassi int
}

Table aluguel {
  id_aluguel int [primary key]
  cd_cliente int [note: 'fk cd_cliente']
  placa char(7) [note: 'fk placa']
  data_inicio datetime
  data_fim datetime
  valor numeric
}

Table reserva {
  id_reserva int [primary key]
  cd_cliente int [note: 'fk cd_cliente']
  placa char(7) [note: 'fk placa']
  data_reserva datetime
  valor numeric
}


https://dbdiagram.io/d/trabalho-banco-665fa71db65d933879843a7e

**Comment by VitorKW** [comment]
![modelo físico](https://github.com/edrikfsteiner/aluguel-carros/assets/134104097/926be115-f14e-4328-afe3-c9a7663fbeeb)

**Comment by VitorKW** [comment]
![modelo físico](https://github.com/edrikfsteiner/aluguel-carros/assets/134104097/da5e3435-5051-4094-89df-2c01c18423c3)

**Comment by edrikfsteiner** [comment]
Table cliente {
  cd_cliente int [primary key]
  nm_cliente varchar(200)
  telefone int
  email varchar(200)
  cpf int
}

Table endereco {
  cd_cliente int
  uf char(2)
  cep char(8)
  cidade varchar(100)
  bairro varchar(50)
  rua varchar(200)
  numero int
}

Table veiculos {
  placa char(7) [primary key]
  ano date
  cor varchar(20)
  modelo int
}

Table aluguel {
  id_aluguel int [primary key]
  cd_cliente int
  placa char(7)
  data_inicio datetime
  data_fim datetime
  valor decimal(11,2)
}

Table pagamento {
  id_aluguel int
  cd_forma_pagamento int
  valor decimal(11,2)
}

Table forma_pagamento {
  cd_forma_pagamento int [primary key]
  tipo_pagamento varchar(20)
}

Table cor {
  id_cor int [primary key]
  cor varchar(20)
}

Table modelo {
id_modelo int [primary key]
modelo varchar(20)
marca varchar(20)
}

Table marca {
  id_marca int [primary key]
  marca varchar(20)
}

Ref: cor.id_cor > veiculos.cor
Ref: modelo.id_modelo > veiculos.modelo

Ref: marca.id_marca > modelo.marca

Ref: cliente.cd_cliente > endereco.cd_cliente

Ref: cliente.cd_cliente > aluguel.cd_cliente
Ref: veiculos.placa > aluguel.placa

Ref: aluguel.id_aluguel > pagamento.id_aluguel
Ref: forma_pagamento.cd_forma_pagamento > pagamento.cd_forma_pagamento

**Comment by gustavoniero** [comment]
https://dbdiagram.io/d/trabalho-banco-6668ca856bc9d447b1724f8d

link atualizado.

**Comment by edrikfsteiner** [comment]
![image](https://github.com/edrikfsteiner/aluguel-carros/assets/163454021/a39ee6be-313c-4681-bcda-115089ef8d60)

**Comment by gustavoniero** [comment]
Diagrama Modelo Físico Finalizado

https://dbdiagram.io/d/trabalho-banco-6668ca856bc9d447b1724f8d

![_trabalho-banco (1)](https://github.com/edrikfsteiner/aluguel-carros/assets/141967161/4eaef344-acac-47ce-8ae8-d0e9854738a7)

**Comment by arturoburigo** [comment]
Fechando issue

**Comment by arturoburigo** [comment]
Reabrindo para mudanca na ordem do endereco / cliente e pagamento/aluguel
